//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaasRM.Extensions.Test.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public int HeaderId { get; set; }
        public string Path { get; set; }
        public string Content1 { get; set; }
    
        public virtual Header Header { get; set; }
    }
}
