//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaasRM.Extensions.Test.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header
    {
        public Header()
        {
            this.Contents = new HashSet<Content>();
        }
    
        public int Id { get; set; }
        public System.Guid PublicId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Content> Contents { get; set; }
    }
}
